---
dataset:
    # dataset
    ds:
        img_size: [96, 96]
        n_channels: 3
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        p:
            dataset: 'eyepacs'
            # data_root: '/home/lkoch/mnt/cin_root/data/eyepacs/'
            data_root: '/gpfs01/berens/data/data/eyepacs'
            subset_params:
                session_image_quality: ["Good", "Excellent"]
                # session_image_quality: ["Adequate", "Good", "Excellent"]
        q:
            dataset: 'eyepacs'
            # data_root: '/home/lkoch/mnt/cin_root/data/eyepacs/'
            data_root: '/gpfs01/berens/data/data/eyepacs'
            subset_params:
                session_image_quality: ["Adequate"]
                # session_image_quality: ["Adequate", "Good", "Excellent"]
    # dataloader
    dl:
        batch_size: 16
        p:
            use_sampling: False
            # sampling_by_variable: 'ethnicity'
            # sampling_weights: [1, 1, 0, 0, 0, 0, 0]
            sampling_by_variable: 'quality'
            sampling_weights: [0, 1, 1, 1]
        q:
            use_sampling: False
            # sampling_by_variable: 'ethnicity'
            # sampling_weights: [0, 1, 0, 0, 0, 0, 0]
            sampling_by_variable: 'quality'
            sampling_weights: [0, 1, 0, 0]
        num_workers: 4
        pin_memory: True
model:
    img_size: 96
    channels: 3
    task_classifier_type: 'camelyon'
    task_classifier_path: './experiments_rebuttal/classification-models/camelyon17_seed9_best_model.pth'
trainer:
    epochs: 1
    learning_rate: 1.e-5
    loss_type: 'mmd2'
    eval:
        n_permute: 100
        alpha: 0.05
        use_tensorboard: True
        n_test_reps: 100
        eval_interval_globalstep: 1
        num_eval_batches: 10
domain_classifier:
    model:
        arch: 'resnet50'
    train:
        epochs: 3
        optimizer: SGD # SGD / ADAM
        learning_rate: 0.001 # initial learning rate
        momentum: 0.9 # only for SGD. set to 0 to disable momentum
        nesterov: True # only for SGD.
        weight_decay: 0.0005 # set to 0 to disable weight decay
        lr_scheduler: True
    eval:
        n_permute: 100
        alpha: 0.05
        use_tensorboard: True
        n_test_reps: 30
        eval_interval_globalstep: 300
        num_eval_batches: 30
        plot_images_first_only: True