---
dataset:
    # dataset
    ds:
        img_size: [96, 96]
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        p:
            dataset: 'eyepacs'
            data_root: '/home/lkoch/mnt/cin_root/data/eyepacs/'
        q:
            dataset: 'eyepacs'
            data_root: '/home/lkoch/mnt/cin_root/data/eyepacs/'
    # dataloader
    dl:
        batch_size: 32
        p:
            use_sampling: True
            sampling_by_variable: 'ethnicity'
            sampling_weights: [1, 0, 0, 0, 0, 0, 0]
        q:
            use_sampling: True
            sampling_by_variable: 'ethnicity'
            sampling_weights: [0, 1, 0, 0, 0, 0, 0]
        num_workers: 4
        pin_memory: True
model:
    img_size: 96
    channels: 3
    task_classifier_type: 'camelyon'
    task_classifier_path: './experiments_rebuttal/classification-models/camelyon17_seed9_best_model.pth'
trainer:
    epochs: 1
    learning_rate: 1.e-5
    loss_type: 'mmd2'
    eval:
        n_permute: 100
        alpha: 0.05
        use_tensorboard: True
        n_test_reps: 100
        eval_interval_globalstep: 1
        num_eval_batches: 10
